### ISSUE TITLE
Сделать модуль оповещения

### ISSUE THREAD

**Issue by Yui-Ezic** [Yui-Ezic/maid-bot#1]
# Введение

Чат-бот будет позволять подписаться на получение оповещений о событиях, которые происходят в чате. Например, событием может быть появления мата в сообщении. Каждый модуль чат-бота может добавлять свои какие-то события и должен оповещать этот модуль о том что событие произошло.  

Модуль оповещения должен предоставлять список возможных способов оповещения а так же форму для заполнения данных, которые нужны для отправки оповещения этим способом.

# Сущности 

## Чат

Чат считается некоторой внешней для модуля сущностью. Внутри модуля мы оперируем только идентификатором чата, который принимаем как аргумент в сценариях требующих этого.

## Событие

```yml
properties:
  id:
    type: string
    description: Уникальный идентификатор
  title:
    type: string
    description: Отображаемое пользователям название события 
  description:
    type: string
    description: Отображаемое пользователям описание события 
  type:
    type: string
    description: Тип события, является уникальным в комбинации с chat_id
  chat_id:
    type: string
    nullable: false
    description:  Идентификатор чата, которому принадлежит событие
  roles:
    type: array
    description: Список идентификаторов ролей, которым доступна подписка на событие
    items:
      type: string
```

## Подписчик

```yml
properties:
  id:
    type: string
    description: Является уникальный в комбинации с chat_id
  roles:
    type: array
    description: Идентификаторы ролей к которым принадлежит подписчик
    items:
      type: string
```

## Роль

```yml
properties:
  id:
    type: string
    description: Уникальный идентификатор роли
  name:
    type: string
    description: Название роли. Является уникальным в комбинации с chat_id
  chat_id:
    type: string
    description: Идентификатор чата к которому относится роль
```

## Подписка

```yml
properties:
  id:
    type: string
    description: Уникальный идентификатор
  event_id:
    type: string
    description: Идентификатор события
  subscriber_id:
    type: array
    description: Идентификатор подписчика
```

# Сценарии использования:

## Подписчик:

- Подписаться на оповещения про события определенного типа внутри чата. Пользователь не может подписаться на события другого чата, а только на глобальные или доступные этому чату. Пользователь может подписаться только на события доступные его роли.
- Отписаться от оповещения про события определенного типа внутри чата. Если пользователь не подписан на события от которого пытается отписаться то ничего не делать и вернуть успешный ответ.
- Посмотреть все события на которые он подписан (внутри чата или вообще). 
- Посмотреть все события на которые можно подписаться.

## Чат-бот:

- Создать подписчика.
- Удалить подписчика.
- Добавить событие. 
- Удалить событие. При этом должны удалится все подписки, которые относятся к этому событию.
- Оповестить, о том, что событие произошло.
